import tkinter as tk
window = tk.Tk()
window.title("test2")
window.geometry("600x400")
var = tk.StringVar()
def insert():
    var = e.get()
    e.clipboard_clear()
    t.insert("insert",var)
e = tk.Entry(window,show="*")
e.pack()
t = tk.Text(window,width=15,height=2)
t.pack()
r1 =  tk.Radiobutton(window,text="aa",variable=var ,value='A',command=insert)
r1.pack()
r2 =  tk.Radiobutton(window,text="bb",variable=var ,value='b',command=insert)
r2.pack()
b = tk.Button(window,width=3,height=1,command=insert,text="hit")
b.pack()
window.mainloop()