import numpy as np
import numpy.matlib
# eye(4)
# print(np.eye(4).shape)
# print(np.array([1,2,3] ,ndmin=2) )
# A = np.array([[1,1],[1,-1]])
# print(np.linalg.inv(A))
# A= np.array([[[1,2,0,3],[2,4,1,0],[3,6,0,9]]])
# print(A.ndim)
# a = np.array([[1,2,3],[4,5,6]]) 
# print(a)
# a.shape =  (3,2)  
# print(a)
# x = np.empty([3,2],dtype="int8")
# print(x)
# print(np.matlib.empty((2,2)).value)
# print(np.ones((2,3)))
# A= np.array([[1,1,1],[0,2,5],[2,5,-1]])
# B=np.array([6,-4,27])
# print(np.linalg.solve(A,B))
# 复合对象
# at = np.dtype([('age',np.int8)])
# a = np.array([(10,),(21,)],dtype=at)
# print(a['age'])
r = np.random.randn(2,3)
print(r)